
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SpotRecommenderModelApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SpotRecommenderModel.ModelInput sampleData = new SpotRecommenderModel.ModelInput()
            {
                Customer_id = 12F,
                Adults = 3F,
                Children = 2F,
                Pets = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = SpotRecommenderModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Spot_id with predicted Spot_id from sample data...\n\n");


            Console.WriteLine($"Customer_id: {12F}");
            Console.WriteLine($"Spot_id: {132F}");
            Console.WriteLine($"Adults: {3F}");
            Console.WriteLine($"Children: {2F}");
            Console.WriteLine($"Pets: {0F}");


            Console.WriteLine($"\n\nPredicted Spot_id: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
